spring:
  profiles:
    active: local
    group:
#      "local": "console-logging"
      "local": "file-logging,console-logging,performance-logging"
      "prod": "file-logging"
  application:
    name: spring-playground
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:13306/test
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 40
  kafka:
    bootstrap-servers: localhost:9092,localhost:9101
    schema-registry:
      url: http://127.0.0.1:8081

  logging:
    level:
      org:
        springframework:
          kafka: DEBUG
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  config: classpath:logback-spring.xml
  level:
    root: info
server:
  tomcat:
    mbeanregistry:
      enabled: true

kakao:
  client:
    id: 20c5e61eca234407fe67e0918dbff845
    secret: LNb25bRip0Xxa8utallgJUTz1ycaWs06
