apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      httpMethod: GET
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: trace_id

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    jsonData:
      derivedFields:
          - datasourceUid: tempo
            matcherRegex: trace_id=([a-f0-9\-]+)
            name: traceID
            url: $${__value.raw}
            label: Trace ID

  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    apiVersion: 1
    uid: tempo
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus
      tracesToLogs:
        datasourceUid: loki
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBySpanID: true
        tags: [ { key: 'service.name', value: 'job' } ]

  - name: Jaeger
    type: jaeger
    uid: jaeger
    access: proxy
    orgId: 1
    url: http://jaeger:16686
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      tracesToLogs: # Linking Jaeger Traces to Loki Logs
        enabled: true
        datasourceUid: loki
        tags:
          - "trace_id"

  - name: Zipkin
    type: zipkin
    uid: zipkin
    access: proxy
    orgId: 1
    url: http://zipkin:9411
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      traceToLogs:
        enabled: true
        datasourceUid: loki
        tags:
          - "traceId"
