server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080
  enable_runtime_reload: true # HTTP 요청으로 리로드 활성화

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push # push할 Loki의 주소

scrape_configs:
  - job_name: my-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: my-app
          service_name: my-app
          __path__: /app/logs/*.log

  # scrape from Kafka connect Docker container
  - job_name: docker_container
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        filters:
          - name: label
            values: [ "logging.promtail.job=connect" ]  # 특정 라벨이 있는 컨테이너만 수집
    relabel_configs:
      - source_labels: [ __meta_docker_container_name ]
        target_label: container_name
      - source_labels: [ container_name ]
        target_label: service_name
      - replacement: "connect"  # {job="docker"}으로 설정
        target_label: job